language: node_js
node_js:
  - "node"
dist: trusty

branches:
    only:
    - master
    - dev
    - staging

install:
    - npm install
    - cd functions && npm install && cd ..;
    - npm install -g firebase-tools
    - npm install -g @angular/cli

script:
    - npm run lint;
    - npm --prefix functions run lint;

    - PACKAGE_VERSION="v$(node -p "require('./package.json').version")"
    - echo $PACKAGE_VERSION

    - npm run loc;

    - if [ $TRAVIS_BRANCH == "dev" ]; then
        npm run build:dev;
      fi
    - if [ $TRAVIS_BRANCH == "staging" ]; then
        npm run build:staging;
      fi
    - if [ $TRAVIS_BRANCH == "master" ]; then
        npm run build:prod;
      fi

after_success:
    - if [ $TRAVIS_BRANCH == "master" ]; then
        firebase use prod;
        firebase functions:config:set stripe.secret_key=$PROD_STRIPE_API_SECRET;
        firebase functions:config:set stripe.webhooks_secret=$PROD_STRIPE_WEBHOOKS_SECRET;
        firebase deploy --project prod --token $FIREBASE_TOKEN --message $PACKAGE_VERSION;
      fi

    - if [ $TRAVIS_BRANCH = "staging" ]; then
        firebase use staging;
        firebase functions:config:set stripe.secret_key=$STAGING_STRIPE_API_SECRET;
        firebase functions:config:set stripe.webhooks_secret=$STAGING_STRIPE_WEBHOOKS_SECRET;
        firebase deploy --project staging --token $FIREBASE_TOKEN --message $PACKAGE_VERSION;
      fi

