language: node_js
node_js:
    - "stable"

branches:
    only:
    - master
    - dev

before_script:
    - npm install -g firebase-tools
    - npm install -g @angular/cli
    - npm install -g webpack
    - cd functions
    - npm install
    - cd ..

script:
    - if [ "$TRAVIS_BRANCH" = "master" ]; then
        ng build --dev;
      fi
    - if [ "$TRAVIS_BRANCH" = "dev" ]; then
        ng build --dev;
      fi

after_success:
    - cd functions
    - webpack
    - cd ..
    - if [ "$TRAVIS_BRANCH" = "master" ]; then
        firebase deploy --project dev --token $FIREBASE_TOKEN;
      fi
    - if [ "$TRAVIS_BRANCH" = "dev" ]; then
        firebase deploy --project dev --token $FIREBASE_TOKEN;
      fi

