language: node_js
node_js:
    - "stable"

branches:
    only:
    - master
    - dev
    - staging

before_script:
    - npm install -g firebase-tools
    - npm install -g @angular/cli
    - npm install -g typescript

script:
    - if [ "$TRAVIS_BRANCH" = "master" ]; then
        ng build --prod --env=prod;
      fi
    - if [ "$TRAVIS_BRANCH" = "staging" ]; then
        ng build --prod --env=staging;
      fi
    - if [ "$TRAVIS_BRANCH" = "dev" ]; then
        ng build --prod --env=dev;
      fi

    - cd functions
    - npm install
    - tsc
    - cd ..

after_success:
    - if [ "$TRAVIS_BRANCH" = "master" ]; then
        firebase deploy --project prod --token $FIREBASE_TOKEN;
      fi
    - if [ "$TRAVIS_BRANCH" = "staging" ]; then
        firebase deploy --project staging --token $FIREBASE_TOKEN;
      fi

