language: node_js
node_js:
    - "stable"

branches:
    only:
    - master
    - dev
    - staging

before_script:
    - cd functions && npm install && cd ..
    - npm install -g firebase-tools
    - npm install -g @angular/cli

script:
    - if [ "$TRAVIS_BRANCH" = "dev" ]; then
        npm run build:dev;
      fi
    - if [ "$TRAVIS_BRANCH" = "staging" ]; then
        npm run build:staging;
      fi
    - if [ "$TRAVIS_BRANCH" = "master" ]; then
        npm run build:prod;
      fi
    - cd functions && npm run build && cd ..;

after_success:
    - if [ "$TRAVIS_BRANCH" = "master" ]; then
        firebase deploy --project prod --token $FIREBASE_TOKEN;
      fi
    - if [ "$TRAVIS_BRANCH" = "staging" ]; then
        firebase deploy --project staging --token $FIREBASE_TOKEN;
      fi

