language: node_js
node_js:
    - "stable"

branches:
    only:
    - master

before_script:
    - npm install -g firebase-tools
    - npm install -g @angular/cli

script:
    - if [ "$BRANCH" == "master" ]; then ng build --dev; fi

after_success:
    - if [ "$BRANCH" == "master" ]; then firebase deploy --project dev --token $FIREBASE_TOKEN; fi

