language: node_js
node_js:
    - "stable"

branches:
    only:
    - master

before_script:
    - npm install -g firebase-tools
    - npm install -g @angular/cli

script:
    - test $TRAVIS_BRANCH = "master" && ng build --dev

after_success:
    - test $TRAVIS_BRANCH = "master" && firebase deploy --project dev --token $FIREBASE_TOKEN

