language: node_js
node_js:
    - "stable"

branches:
    only:
    - master
    - dev
    - staging
    
before_script:
    - npm install -g firebase-tools
    - npm install -g @angular/cli

script:
    - if [ "$TRAVIS_BRANCH" = "master" ]; then
        ng build --prod --env=dev;
      fi
    - if [ "$TRAVIS_BRANCH" = "dev" ]; then
        ng build --prod --env=dev;
      fi

after_success:
    - if [ "$TRAVIS_BRANCH" = "master" ]; then
        firebase deploy --project dev --token $FIREBASE_TOKEN;
      fi
    - if [ "$TRAVIS_BRANCH" = "dev" ]; then
        firebase deploy --project dev --token $FIREBASE_TOKEN;
      fi

